### ISSUE TITLE
landing Not found if Private Repo

### ISSUE THREAD

**Issue by hiphapis** [dittos/diffmonster#24]
한국말로 해야하나, 영어로 해야하나 고민하다.. 일단 한국어로 남겨요 ㅎㅎ
Private Repo여서 로그인을 하라해서 아래 화면에 있는 링크를 눌렀는데도, 여전히 아래 화면으로 랜딩되네요.
![image](https://user-images.githubusercontent.com/18629/28047946-a2efde3a-6628-11e7-82e1-12122115a68f.png)

**Comment by dittos** [comment]
안녕하세요! 일단 로그인이 정상적으로 되신 건지 알고 싶은데요. 헤더 오른쪽에 사용자명이 뜨는지 궁금합니다.
